name: Python Package using Conda

on: [push]

name: Work of Proof Blockchain

on:
  release:
    types: [created]
  push:
    branches:
      - main
      - unittest
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: workflow
      run: |
        make workflow
